export const ITEMS_FETCH_REQUEST = 'ITEMS_FETCH_REQUEST';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_DELETE_SUCCESS = 'ITEMS_DELETE_SUCCESS';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_ADD = 'ITEMS_ADD';

export const LABS_ADD_REQUEST = 'LABS_ADD_REQUEST';
export const LABS_ADD_SUCCESS = 'LABS_ADD_SUCCESS';
export const LABS_UPDATE_REQUEST = 'LABS_UPDATE_REQUEST';
export const LABS_UPDATE_SUCCESS = 'LABS_UPDATE_SUCCESS';

export const LABS_FETCH_REQUEST = 'LABS_FETCH_REQUEST';
export const LABS_FETCH_SUCCESS = 'LABS_FETCH_SUCCESS';
export const LABS_HAS_ERRORED = 'LABS_HAS_ERRORED';
export const LABS_CLEAR_DATA = 'LABS_CLEAR_DATA';
